### ISSUE TITLE
Multiselect on the right side of grid

### ISSUE THREAD

**Issue by protstein** [free-jqgrid/free-jqgrid.github.io#1]
I was using this workaround to place check-boxes on the right side of my grid (multiselectSide: "left"):  
https://github.com/tonytomov/jqGrid/pull/451/files

It would be great if this fix could be Incorporated into the free-jqGrid code.

**Comment by OlegKi** [comment]
Thank you for your feedback! I will analyse your code. I think that one need to do some additional changes in case of usage data grouping additionally at least in case of `groupSummaryPos: ["header"]`. I prefer to support new features in all cases of usage jqGrid if it's possible.

I plan to implement the feature, but I want to allow to specify `"left"`, `"right"` and `"none"` position for the checkbox columns. The problem is that one more common case is hiding the checkbox column. It has some additional performance advantages in case of large number of rows. Selection of the row itself (adding the `ui-state-highlight` class) works much more quickly as checking/unchecking of the checkbox from the "cb" column. One sees this clear in case of usage Select All/Unselect All with large number of rows.

By the way I improved the performance of selection/unselection of rows in the current version of free jqGrid on GitHub (after publishing free jqGrid 4.8).

Three additional feature, which I plan to implement in free jqGrid very soon:
- Windows style of selection where one can combine selection with Shift and Ctrl keys.
- persistent state of selection over paging (at least in case of usage local data)
- support of multiselect in TreeGrid

I will post additional comments to your later.

Best regards
Oleg
P.S. The place https://github.com/free-jqgrid/free-jqgrid.github.io is reserved for the web site with the new documentation of free jqGrid. You should better post new issues in the future with suggestions of bug fixes to https://github.com/free-jqgrid/jqGrid/issues.

**Comment by protstein** [comment]
Dear Oleg,

Thank you for your rapid and thoughtful response.  I will make sure to post future requests for enhancements/bug fixes to the correct website: https://github.com/free-jqgrid/jqGrid/issues.

Let me take a moment to thank you for your continued support of jqGrid (free) and all of your wonderful suggestions and demo's throughout StackOverflow over the years.  Your help has been invaluable to me and my development team.   I hope you know how much you are appreciated!

I am glad to hear that you plan to implement the multiselect positioning in future free jqGrid release.  I understand the need to hide the checkbox column for performance improvement.     Thanks for explaining to me the details of implementing this fix.

I look forward to all of the future improvements of free jqGrid especially the persistence of selection in local storage.  We use your code from demos to accomplish this on our grids and it would be great to have it incorporated as a feature of jqGrid!

Thank you for your time and consideration,
Peg

**Comment by OlegKi** [comment]
Hi Peg,

Thank you for the good words which you wrote in your last comment. It stimulate me additionally to make some other changes which I planed before. I rewritten many parts of old jqGrid code and now the postion of multiselect, rownumbers and subgrid columns can be on any position. Look in the comment of [the last commit](https://github.com/free-jqgrid/jqGrid/commit/31949327ebcce35b74a3688f059837f1967a1fe2). It describes shortly the new `multiselectPosition` option. You can use `multiselectPosition: "right"`. By the way the latest changes should makes additional performance improvement too.

Best wishes to you!
Oleg
