### ISSUE TITLE
JavaScript runtime error: 'getGridRes' is undefined

### ISSUE THREAD

**Issue by asifali0869** [free-jqgrid/free-jqgrid.github.io#11]
After updating to latest release , i get following error when pressing delete button (inline/form edit).

Unhandled exception at line 1, column 33297 in  free-jqGrid/modules/min/grid.formedit.js

0x800a1391 - JavaScript runtime error: 'getGridRes' is undefined .

I have also made sured that file  jquery.jqgrid.src.js is added.

**Comment by OlegKi** [comment]
Thanks for the bug report! I posted the corresponding fix [here](https://github.com/free-jqgrid/jqGrid/commit/6cbea6e087cdc981c75296c9007affd4b353420d).

Please post issues in the future to https://github.com/free-jqgrid/jqGrid/issues instead of https://github.com/free-jqgrid/free-jqgrid.github.io/issues because the repository free-jqgrid.github.io is only for **documentation** of free jqGrid (see [here](https://free-jqgrid.github.io/index.html)) and not for the product itself.
