### ISSUE TITLE
setCell with empty string, does not change existing value

### ISSUE THREAD

**Issue by imranakram** [free-jqgrid/free-jqgrid.github.io#3]
I have a column like this 
 {name: 'ContactPhone', index: 'ContactPhone', editable: false, width: '100'},
When I assign an empty string to the cell. It doesn't change the value.

**Comment by OlegKi** [comment]
Please use https://github.com/free-jqgrid/jqGrid/issues instead of https://github.com/free-jqgrid/free-jqgrid.github.io/issues/. The repository _free-jqgrid.github.io_ are reserved **for documentation** about free jqGrid only.

You wrote "I assign an empty string to the cell" without any details. There are many ways to do this, moreover one don't place the empty string directly in `<td>` because of problems in some web browsers. Typically it means that one set `&nbsp;` instead of empty string.

Nevertheless I imagine the situation where you have `newValue` variable with new content of the cell and the value of the `newValue` variable _could be_ empty. I the case you can use the code like below

``` JavaScript
$("#grid").jqGrid("setCell", rowid, colName, newValue, false, false, true);
```

The last parameter of `setCell` method (`true` above) can be used to force update the cell event if `newValue` is empty string.

The mast remark. I recommend you to replace the definition of the column `ContactPhone` which you posted to the following:

``` JavaScript
{name: 'ContactPhone', width: 100}
```
1. The `index` value should be not used if it have the same value like `name` property.
2. The default value of property `editable` is already `false`. There are a lot of other properties in `colModel`. It's better don't include ll the properties if the corresponding value is default value.
3. The expected type of `width` property is number. So `100` is more correct as `'100'`.

**Comment by imranakram** [comment]
Thanks @OlegKi, appreciate the details and sorry for using the wrong forum.
